# Generated by Django 5.1.6 on 2025-02-28 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.UUID('bf4d23f8-3171-4ff2-8b1c-401449e59212'), primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('srno', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='imgcompress.processingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_img_url', models.URLField(blank=True, null=True)),
                ('compressed_img_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='imgcompress.product')),
            ],
        ),
    ]
