# Generated by Django 5.1.6 on 2025-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgcompress', '0002_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrequest',
            name='csv_output_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
